version: "3.7"

services:
  nginx:
    build: ./nginx
    container_name: ${PREFIX}_nginx
    depends_on:
      - app
    volumes:
      - ../:/var/www:delegated
      - ./nginx/sites/:/etc/nginx/conf.d:delegated
    ports:
      - "80:80"
    networks:
      - network

  app:
    build:
      context: ./app
      args:
        - VERSION=${PHP_VERSION}
    container_name: ${PREFIX}_app
    working_dir: /var/www

    environment:
      COMPOSER_MEMORY_LIMIT: 2G
      XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_STORM_PORT} remote_enable=1
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    volumes:
      - ../:/var/www:delegated
      - ./app/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini:delegated
    expose:
      - "9000"
    networks:
      - network

  mysql:
    build:
      context: ./mysql
      args:
        - VERSION=${MYSQL_VERSION}
    ports:
      - "3306:3306"
    container_name: ${PREFIX}_mysql

    depends_on:
      - app
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - network

  redis:
    build:
      context: ./redis
      args:
        - VERSION=${REDIS_VERSION}
    container_name: ${PREFIX}_redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - network

networks:
  network:
    driver: bridge
    name: ${PREFIX}_network
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}/${SUBNET_MASK}
